# ERPNext v15 Docker Compose Configuration
# Run with: docker compose -f docker-compose-v15.yml up -d

name: erpnext-v15

services:
  backend-v15:
    image: frappe/erpnext:v15
    container_name: backend-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db-v15
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator-v15:
    image: frappe/erpnext:v15
    container_name: configurator-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db-v15
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache-v15:6379
      REDIS_QUEUE: redis-queue-v15:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs

  create-site-v15:
    image: frappe/erpnext:v15
    container_name: create-site-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db-v15:3306;
        wait-for-it -t 120 redis-cache-v15:6379;
        wait-for-it -t 120 redis-queue-v15:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend-v15;

  db-v15:
    image: mariadb:10.6
    container_name: db-v15
    networks:
      - frappe_network_v15
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --bind-address=0.0.0.0
      - --binlog-format=ROW
      - --log-bin=mysql-bin
      - --server-id=1
      - --binlog-row-image=FULL
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data-v15:/var/lib/mysql

  frontend-v15:
    image: frappe/erpnext:v15
    container_name: frontend-v15
    networks:
      - frappe_network_v15
    depends_on:
      - websocket-v15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend-v15:8000
      FRAPPE_SITE_NAME_HEADER: frontend-v15
      SOCKETIO: websocket-v15:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs
    ports:
      - "8081:8080"

  queue-long-v15:
    image: frappe/erpnext:v15
    container_name: queue-long-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs

  queue-short-v15:
    image: frappe/erpnext:v15
    container_name: queue-short-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs

  redis-queue-v15:
    image: redis:6.2-alpine
    container_name: redis-queue-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data-v15:/data

  redis-cache-v15:
    image: redis:6.2-alpine
    container_name: redis-cache-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data-v15:/data

  scheduler-v15:
    image: frappe/erpnext:v15
    container_name: scheduler-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs

  websocket-v15:
    image: frappe/erpnext:v15
    container_name: websocket-v15
    networks:
      - frappe_network_v15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites-v15:/home/frappe/frappe-bench/sites
      - logs-v15:/home/frappe/frappe-bench/logs

volumes:
  db-data-v15:
  redis-queue-data-v15:
  redis-cache-data-v15:
  sites-v15:
  logs-v15:

networks:
  frappe_network_v15:
    driver: bridge
