name: erpnext
displayName: ERPNext ERP System
description: ERPNext open-source ERP system with Frappe framework

database:
  type: mysql
  tablePrefix: tab
  idField: name
  timestampFields:
    created: creation
    modified: modified
    modifiedBy: modified_by
  timezoneOffsetHours: 7
  # Tables used to detect this is an ERPNext database
  discoveryTables:
    - tabDocType
    - tabUser
    - tabEmployee
    - tabCompany

blockchain:
  apiEndpoint: ${API_ENDPOINT:-http://127.0.0.1:4001}

kafka:
  topicPrefix: erpnext

tables:
  - name: tabEmployee
    displayName: Employee
    endpoint: /employees
    dataKey: employeeData
    fields:
      - name
      - employee
      - first_name
      - middle_name
      - last_name
      - employee_name
      - gender
      - date_of_birth
      - date_of_joining
      - status
      - company
      - department
      - designation
      - employee_number
      - reports_to
      - branch
      - cell_number
      - personal_email
      - company_email
      - current_address
      - permanent_address
      - emergency_phone_number
      - marital_status
      - blood_group
      - salary_currency
      - salary_mode
      - bank_name
      - bank_ac_no
      - employment_type
      - grade
      - default_shift

  - name: tabAttendance
    displayName: Attendance
    endpoint: /attendances
    dataKey: attendanceData
    fields:
      - name
      - employee
      - employee_name
      - attendance_date
      - status
      - working_hours
      - in_time
      - out_time
      - late_entry
      - early_exit
      - shift
      - company
      - department

  - name: tabUser
    displayName: User
    endpoint: /users
    dataKey: userData
    fields:
      - name
      - email
      - first_name
      - last_name
      - full_name
      - username
      - enabled
      - user_type
      - last_login

  - name: tabTask
    displayName: Task
    endpoint: /tasks
    dataKey: taskData
    fields:
      - name
      - subject
      - project
      - status
      - priority
      - description
      - exp_start_date
      - exp_end_date
      - completed_on
      - assigned_to

  - name: tabCompany
    displayName: Company
    endpoint: /companies
    dataKey: companyData
    fields:
      - name
      - company_name
      - abbr
      - default_currency
      - country
      - domain
